name: As He Creates So He Destroys
on:
  push:
    branches: [$default-branch, shain/*]
  pull_request:
    branches: [$default-branch]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Ch-ch-ch-check it out
      uses: actions/checkout@v3
    - name: Read dependencies.json
      id: deps
      uses: juliangruber/read-file-action@v1
      with:
        path: ./testdep.json
        # path: ./dependencies.json
    - name: Clone zlib
      uses: actions/checkout@v3
      with:
        repository: ${{ fromJson(steps.deps.outputs.content).zlib.url }}
        ref: ${{ fromJson(steps.deps.outputs.content).zlib.tag }}

    # - name: Build zlib
    #   run: git clone--bare --no-checkout \
    #     --branch ${{ fromJson(steps.deps.outputs.content).zlib.tag }} \
    #     ${{ fromJson(steps.deps.outputs.content).zlib.url }} && \
    #     cd zlib && \
    #     configure --prefix=/awesome/output && \
    #     make && make install
    # - name: Build zlib
    #   run: cd zpmake


    # - name: Prep GCC
    #   run: echo "${{ steps.deps.outputs.content }}"
    # - name: Prep MPFR
    #   run: echo "git clone --depth 1 -b ${{ fromJson(steps.deps.outputs.content).mpfr.tag }} ${{ fromJson(steps.deps.outputs.content).mpfr.url }}"
    # - name: Prep MPC
    #   run: echo "git clone --depth 1 -b ${{ fromJson(steps.deps.outputs.content).mpfr.tag }} ${{ fromJson(steps.deps.outputs.content).mpfr.url }}"
    # - name: Prep GMP
    #   run: echo "git clone --depth 1 -b ${{ fromJson(steps.deps.outputs.content).mpfr.tag }} ${{ fromJson(steps.deps.outputs.content).mpfr.url }}"
