name: As He Creates So He Destroys
on:
  push:
    branches: [$default-branch, shain/*]
  pull_request:
    branches: [$default-branch]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Ch-ch-ch-check it out
      uses: actions/checkout@v3
    - name: Read dependencies.json
      id: deps
      uses: juliangruber/read-file-action@v1
      with:
        path: ./dependencies.json
    - name: Parse test 1
      run: echo "${{ steps.deps.outputs.content }}"
    - name: Parse test 2
      run: echo "git clone --depth 1 -b ${{ fromJson(steps.deps.outputs.content).mpfr.vers }} ${{ fromJson(steps.deps.outputs.content).mpfr.url }}"

    # - name: Checkout MPFR
    #   uses: actions/checkout@v3
    #   run: git clone --depth 1 -b 4.2.0 https://gitlab.inria.fr/mpfr/mpfr


    # - name: Install pylint
    #   run: pip install Pylint
    # - name: Linting